### ISSUE TITLE
multiple build issues

### ISSUE THREAD

**Issue by urherenow** [devkitPro/3ds_portlibs#22] opened 2017-05-05 09:16 UTC
tremor <- expects arm-none-eabi-pkg-config to be an executable or command? building from msys instead of cmd gets past that, but then it hangs on:

checking for OGG... yes
./configure: line 11719: syntax error near unexpected token `,'
./configure: line 11719: `    XIPH_PATH_OGG(, as_fn_error $? "must have Ogg installed!" "$LINENO" 5)'
make: *** [tremor] Error 2

tinyxml2 <-builds fine... until you try to make install

libxml2 <-seems to build from msys until make install, then same as #15
EDIT: The problem with installing libxml2 seems to be caused by either the version or build options of zlib.

I also added the latest cmake to devkitpro\msys\

**Comment by ahoischen** [comment] 2017-05-07 09:11
I can confirm all these issues on both my personal system and multiple Ubuntu and Debian docker images. The tremor issue is already being tracked by #9 which has been prematurely closed.

**Comment by joel16** [comment] 2017-05-20 23:02
I can confirm the issues are on my side as well. 
Got over "tremor <- expects arm-none-eabi-pkg-config" by using $(CURDIR) instead of $(PWD) to find PKG_CONFIG. 

But the issue persists:
"./configure: line 11719: syntax error near unexpected token ,' ./configure: line 11719: XIPH_PATH_OGG(, as_fn_error $? "must have Ogg installed!" "$LINENO" 5)'
make: *** [tremor] Error 2"

**Comment by WinterMute** [comment] 2017-07-30 13:38
The XIPH_PATH_OGG issue tells you what the problem is and how to fix it. 

As for the rest of the problems here, this is a very poor way to report issues. For future reference please report **one** problem per issue. I'm going to make a policy of closing issues that use the word multiple without bothering to read them.

**Closed as completed by WinterMute** 2017-07-30 13:38 UTC
